[build]
  functions = "functions"
[functions]
  node_bundler = "esbuild"
  node_sourcemap = true
[functions.app]
  external_node_modules = ["express"]
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200
  force = true